frase = ('curso em video python')
print(frase[9])
print(frase[9:14])
print(frase[9:14:2])
print(frase[:21])
print(len(frase))
print(frase.count('e'))
print(frase.find('deo'))
print('curso' in frase)
print (frase.replace("python", "android"))
print(frase.split())